-- One-time backlog reset. ~85% of the accumulated open findings were artifacts
-- of pipeline defects fixed in code alongside this migration:
--   * Tier 4 reconciled a multi-year statement backfill (2022→) against books
--     that only start 2025-01 — every old bank line became a CRITICAL
--     "unrecorded disbursement" (T4-02/07/09).
--   * Check-number matching had no date constraint, so recycled check numbers
--     paired years-apart transactions into false CRITICAL "alterations" (T4-04).
--   * The books contain no receipt/deposit transactions, so EVERY bank deposit
--     was an "unexplained inflow" (T4-07).
--   * T1-09 flagged per payment (now aggregates per vendor, credits included),
--     T1-04 counted every small payment (now floored), T2-10 is now quarterly.
--
-- Open rows from those rule families are ARCHIVED (full snapshot, auditable)
-- and removed; the next weekly run regenerates the true set under the fixed
-- code. Human-dispositioned rows are never touched — disposition memory keeps
-- honoring them. Check-image findings (T4-03/05, image-sourced T4-04) are kept:
-- they come from vision reads that may not be re-run for older statements.

create table if not exists financial_forensics.findings_archive
  as select * from financial_forensics.findings where false;
alter table financial_forensics.findings_archive
  add column if not exists archived_at timestamptz not null default now(),
  add column if not exists archive_reason text;
alter table financial_forensics.findings_archive enable row level security;

with doomed as (
  select id,
    case
      when rule_id in ('T4-02','T4-07','T4-09') then
        'books-coverage / no-receipts artifact — regenerated by the coverage-scoped reconciler'
      when rule_id = 'T4-04' then
        'cross-era check-number collision — regenerated by the date-constrained matcher'
      when rule_id = 'T4-06' then
        'regenerated by the date-constrained matcher'
      when rule_id = 'T1-09' then
        'superseded by the per-vendor aggregated form (credits + on-account aware)'
      when rule_id = 'T1-04' then
        'superseded by the near-threshold-floored rule'
      when rule_id = 'T2-10' then
        'rule moved to quarterly trend review'
    end as reason
  from financial_forensics.findings
  where disposition = 'open'
    and (
      rule_id in ('T4-02','T4-06','T4-07','T4-09','T1-09','T1-04','T2-10')
      -- T4-04 only in its reconcile (statement-register) form; image reads keep
      or (rule_id = 'T4-04' and details ? 'cleared')
    )
),
archived as (
  insert into financial_forensics.findings_archive
  select f.*, now(), d.reason
  from financial_forensics.findings f
  join doomed d on d.id = f.id
  returning id
)
delete from financial_forensics.findings f
 using archived a
 where f.id = a.id;
