-- One-time T1-02 backlog reset (same pattern as 0014). The 2026-07-07 run was
-- the first over the newly ingested credit-card history (18 months of charges),
-- and T1-02 pairwise-flagged every same-amount card charge within its 10-day
-- window: ad-platform threshold billing (Facebook charged $87.00 87 times,
-- near-daily) became ~1.8k CRITICAL "duplicate" pairs — cadence, not duplicates.
--
-- The rule is fixed alongside this migration: high-frequency cadence clusters
-- (5+ equal amounts, median gap < 15 days) collapse into one INFO summary each,
-- and card-card pairs that aren't a same-day equal-amount double-swipe emit at
-- MEDIUM. Because findings persist with ON CONFLICT DO NOTHING, the recalibrated
-- severities/summaries can only materialize if the artifact rows are cleared:
-- open T1-02 rows are ARCHIVED (full snapshot, auditable) and removed; the next
-- weekly run regenerates the true set under the fixed rule. Human-dispositioned
-- rows are never touched — disposition memory keeps honoring them.

create table if not exists financial_forensics.findings_archive
  as select * from financial_forensics.findings where false;
alter table financial_forensics.findings_archive
  add column if not exists archived_at timestamptz not null default now(),
  add column if not exists archive_reason text;
alter table financial_forensics.findings_archive enable row level security;

with doomed as (
  select id,
    'high-frequency billing-cadence artifact (card threshold/subscription charges) — regenerated by the cadence-aware, severity-calibrated T1-02'
      as reason
  from financial_forensics.findings
  where disposition = 'open' and rule_id = 'T1-02'
),
archived as (
  insert into financial_forensics.findings_archive
  select f.*, now(), d.reason
  from financial_forensics.findings f
  join doomed d on d.id = f.id
  returning id
)
delete from financial_forensics.findings f
 using archived a
 where f.id = a.id;
